Use the base image (gclub/skywardai) instead and change the working directory to /app.
SkywardAI/chat-backend pull request #61
Opened 2024-03-28 09:14 UTC by arvin936

Use the base image (gclub/skywardai) instead and change the working directory to /app.

**Description**

Use base images to reduce build steps and build time.
The Image working directory is unified into the /app directory that is commonly used in open source projects.
This PR fixes #57

**Notes for Reviewers**

**[Signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)**
- [ ] Yes, I signed my commits.

2024-03-28 10:58 UTC, Aisuko requested changes

2024-03-28 10:58 UTC, Aisuko commented on backend/Dockerfile
> +RUN chmod +x /app/entrypoint.sh
As we discussed, could we leave a correct permission to the entrypoint.sh. So, we can copy it to container directly.

2024-03-28 11:06 UTC, Aisuko commented on backend/Dockerfile
> +RUN chmod +x /app/entrypoint.sh
Here is another request see https://github.com/SkywardAI/containers/issues/1

2024-03-28 23:36 UTC, Aisuko reviewed
We should fix the security issue of the base image, and then merge this one.

2024-03-29 09:32 UTC, Micost approved these changes

2024-03-29 22:04 UTC, Aisuko commented
@Micost @arvin936 As we discussed, we should remove this chmod. It will not be supported in multiple-platforms build.

2024-04-01 03:44 UTC, Aisuko commented
Close by #72

2024-04-01 03:44 UTC, closed without merging