feat:Fetch chat history to create combined the prompt for pipeine
SkywardAI/chat-backend pull request #99
Opened 2024-04-12 04:25 UTC by jinronga

**Description**
This PR add Fetch chat history to create combined the prompt for pipeine
This PR is related to https://github.com/SkywardAI/chat-backend/issues/82

**[Signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)**
- [ ] Yes, I signed my commits.

2024-04-12 04:39 UTC, Aisuko commented
@jinronga hi, sign-off please https://github.com/SkywardAI/chat-backend/pull/99/checks?check_run_id=23738305185

2024-04-13 06:46 UTC, Aisuko requested changes

2024-04-13 06:46 UTC, Aisuko commented on .github/release-drafter.yml
> +tag-template: 'v$RESOLVED_VERSION 🌈'
Remove this file from the commit

2024-04-14 05:55 UTC, Micost commented
Close this PR per request

2024-04-14 05:55 UTC, closed without merging